---
# Demo ACI Playbook
- name: Configuring Example Tenant
  hosts: all
  connection: local
  gather_facts: no
  collections:
  - cisco.aci

  tasks:
  - name: Create a New Tenant
    aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "CiscoLive_AWX"
        description: "Tenant configured by Ansible AWX"
        validate_certs: no
        state: present

