---
# Demo ACI Playbook with AWX
- name: Configuring Example Tenant
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: Create a New Tenant
    cisco.aci.aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "CiscoLive_AWX"
        description: "Tenant configured by Ansible AWX"
        validate_certs: no
        state: present

