---
# Demo ACI Playbook
- name: Configuring Example Tenant
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: Create ansible-VRF
    aci_vrf:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "CiscoLive_AWX"
      vrf: "cl_vrf"
      description: "VRF configured by AWX"
      validate_certs: no
      state: present

